package com.YY.model;

// Generated 2015-1-29 16:46:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbGame generated by hbm2java
 */
@Entity
@Table(name = "tb_game", catalog = "platformanage")
public class TbGame implements java.io.Serializable {

	private int id;
	private String gameId;
	private String userId;
	private String gameName;
	private Date gameModifyTime;
	private String gameIntroduce;
	private String gameIcon;
	private String gamePicture;
	private String gameVideo;
	private String gameDownload;
	private String gameGit;
	private String gameTab;
	private Integer gameCommentSum;
	private Integer gameBrowseSum;
	private Integer gameSupportSum;
	private Integer gameOpposeSum;
	private Integer gameDownloadSum;
	private Integer gameGrade;
	private Integer isDeleted;

	public TbGame() {
	}

	public TbGame(int id) {
		this.id = id;
	}

	public TbGame(int id, String gameId, String userId, String gameName, Date gameModifyTime, String gameIntroduce,
			String gameIcon, String gamePicture, String gameVideo, String gameDownload, String gameGit, String gameTab,
			Integer gameCommentSum, Integer gameBrowseSum, Integer gameSupportSum, Integer gameOpposeSum,
			Integer gameDownloadSum, Integer gameGrade, Integer isDeleted) {
		this.id = id;
		this.gameId = gameId;
		this.userId = userId;
		this.gameName = gameName;
		this.gameModifyTime = gameModifyTime;
		this.gameIntroduce = gameIntroduce;
		this.gameIcon = gameIcon;
		this.gamePicture = gamePicture;
		this.gameVideo = gameVideo;
		this.gameDownload = gameDownload;
		this.gameGit = gameGit;
		this.gameTab = gameTab;
		this.gameCommentSum = gameCommentSum;
		this.gameBrowseSum = gameBrowseSum;
		this.gameSupportSum = gameSupportSum;
		this.gameOpposeSum = gameOpposeSum;
		this.gameDownloadSum = gameDownloadSum;
		this.gameGrade = gameGrade;
		this.isDeleted = isDeleted;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "gameId")
	public String getGameId() {
		return this.gameId;
	}

	public void setGameId(String gameId) {
		this.gameId = gameId;
	}

	@Column(name = "userId")
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "gameName")
	public String getGameName() {
		return this.gameName;
	}

	public void setGameName(String gameName) {
		this.gameName = gameName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "gameModifyTime", length = 0)
	public Date getGameModifyTime() {
		return this.gameModifyTime;
	}

	public void setGameModifyTime(Date gameModifyTime) {
		this.gameModifyTime = gameModifyTime;
	}

	@Column(name = "gameIntroduce", length = 65535)
	public String getGameIntroduce() {
		return this.gameIntroduce;
	}

	public void setGameIntroduce(String gameIntroduce) {
		this.gameIntroduce = gameIntroduce;
	}

	@Column(name = "gameIcon")
	public String getGameIcon() {
		return this.gameIcon;
	}

	public void setGameIcon(String gameIcon) {
		this.gameIcon = gameIcon;
	}

	@Column(name = "gamePicture")
	public String getGamePicture() {
		return this.gamePicture;
	}

	public void setGamePicture(String gamePicture) {
		this.gamePicture = gamePicture;
	}

	@Column(name = "gameVideo")
	public String getGameVideo() {
		return this.gameVideo;
	}

	public void setGameVideo(String gameVideo) {
		this.gameVideo = gameVideo;
	}

	@Column(name = "gameDownload")
	public String getGameDownload() {
		return this.gameDownload;
	}

	public void setGameDownload(String gameDownload) {
		this.gameDownload = gameDownload;
	}

	@Column(name = "gameGit")
	public String getGameGit() {
		return this.gameGit;
	}

	public void setGameGit(String gameGit) {
		this.gameGit = gameGit;
	}

	@Column(name = "gameTab")
	public String getGameTab() {
		return this.gameTab;
	}

	public void setGameTab(String gameTab) {
		this.gameTab = gameTab;
	}

	@Column(name = "gameCommentSum")
	public Integer getGameCommentSum() {
		return this.gameCommentSum;
	}

	public void setGameCommentSum(Integer gameCommentSum) {
		this.gameCommentSum = gameCommentSum;
	}

	@Column(name = "gameBrowseSum")
	public Integer getGameBrowseSum() {
		return this.gameBrowseSum;
	}

	public void setGameBrowseSum(Integer gameBrowseSum) {
		this.gameBrowseSum = gameBrowseSum;
	}

	@Column(name = "gameSupportSum")
	public Integer getGameSupportSum() {
		return this.gameSupportSum;
	}

	public void setGameSupportSum(Integer gameSupportSum) {
		this.gameSupportSum = gameSupportSum;
	}

	@Column(name = "gameOpposeSum")
	public Integer getGameOpposeSum() {
		return this.gameOpposeSum;
	}

	public void setGameOpposeSum(Integer gameOpposeSum) {
		this.gameOpposeSum = gameOpposeSum;
	}

	@Column(name = "gameDownloadSum")
	public Integer getGameDownloadSum() {
		return this.gameDownloadSum;
	}

	public void setGameDownloadSum(Integer gameDownloadSum) {
		this.gameDownloadSum = gameDownloadSum;
	}

	@Column(name = "gameGrade")
	public Integer getGameGrade() {
		return this.gameGrade;
	}

	public void setGameGrade(Integer gameGrade) {
		this.gameGrade = gameGrade;
	}

	@Column(name = "isDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

}
