package com.YY.model;

// Generated 2015-1-29 16:46:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbUser generated by hbm2java
 */
@Entity
@Table(name = "tb_user", catalog = "platformanage")
public class TbUser implements java.io.Serializable {

	private int id;
	private String userId;
	private String userEmail;
	private String userName;
	private String password;
	private Integer roleId;
	private Date useRegisterTime;
	private Date userLoginTime;
	private Integer isLogin;
	private Integer isDeleted;

	public TbUser() {
	}

	public TbUser(int id) {
		this.id = id;
	}

	public TbUser(int id, String userId, String userEmail, String userName, String password, Integer roleId,
			Date useRegisterTime, Date userLoginTime, Integer isLogin, Integer isDeleted) {
		this.id = id;
		this.userId = userId;
		this.userEmail = userEmail;
		this.userName = userName;
		this.password = password;
		this.roleId = roleId;
		this.useRegisterTime = useRegisterTime;
		this.userLoginTime = userLoginTime;
		this.isLogin = isLogin;
		this.isDeleted = isDeleted;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "userId")
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "userEmail")
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "userName")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "roleId")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "useRegisterTime", length = 0)
	public Date getUseRegisterTime() {
		return this.useRegisterTime;
	}

	public void setUseRegisterTime(Date useRegisterTime) {
		this.useRegisterTime = useRegisterTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "userLoginTime", length = 0)
	public Date getUserLoginTime() {
		return this.userLoginTime;
	}

	public void setUserLoginTime(Date userLoginTime) {
		this.userLoginTime = userLoginTime;
	}

	@Column(name = "isLogin")
	public Integer getIsLogin() {
		return this.isLogin;
	}

	public void setIsLogin(Integer isLogin) {
		this.isLogin = isLogin;
	}

	@Column(name = "isDeleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

}
